version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "justeat/httpclient-interception"
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "justeat/httpclient-interception"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: Microsoft.AspNetCore.WebUtilities
  - dependency-name: Newtonsoft.Json
  - dependency-name: System.Net.Http
